# Generated by Django 4.1.3 on 2022-11-08 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DemijohnBackend", "0003_user_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("bottle", models.IntegerField()),
                ("water_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="color",
        ),
        migrations.AddField(
            model_name="user",
            name="recurring_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="cart",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="DemijohnBackend.cart",
            ),
        ),
    ]
