# Generated by Django 4.1.3 on 2022-11-08 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "DemijohnBackend",
            "0004_cart_remove_user_color_user_recurring_order_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PreviousOrder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("bottle", models.IntegerField()),
                ("water_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="previous_orders",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="DemijohnBackend.previousorder",
            ),
        ),
    ]
