# Generated by Django 4.1.3 on 2022-11-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DemijohnBackend", "0005_previousorder_user_previous_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
