# Generated by Django 4.1.3 on 2022-11-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DemijohnBackend", "0006_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=50),
        ),
    ]
