# Generated by Django 4.1.3 on 2022-12-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "DemijohnBackend",
            "0009_remove_user_cart_remove_user_previous_orders_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
